active_grasp:
  frame_id: task
  base_frame_id: panda_link0
  ee_frame_id: panda_hand
  ee_grasp_offset: [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.06]
  camera_name: cam
vgn:
  model: $(find vgn)/data/models/vgn_conv.pth
